# Example for String operation using find command

In [3]:
string = 'rahululul'
lookingfor = input('What are you looking for: ')
flag = False
pos = -1
n = len(string)
while True:
    pos = string.find(lookingfor, pos+1, n)
    if pos==-1:
        break
    else:
        print('Found at index: ', pos)
        flag = True
if flag == False:
    print('Not Found')

What are you looking for: l
Found at index:  4
Found at index:  6
Found at index:  8


# Regular Expressions

In [4]:
import re

**Regular Expression Documentation https://docs.python.org/3/library/re.html**

Important RE module functions 

finditer()

match()

fullmatch()

search()

findall()

sub()

subn()

split()

**Finditer() - It finds the iteration of the characters**

**[abc] - We are looking for a or b or c**

**[^abc] - We are looking for except a or b or c**

**[a-z] - All the small letters**

**[A-Z] - All the capital letters**

**[a-zA-Z] - All letter no matter its caps or small**

**[0-9] - All the numbers**

**[a-zA-Z0-9] - All the numbers and alphabets**

**[^a-zA-Z0-9] - All the special characters**

In [6]:
for i in re.finditer('[abc]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
2 ... 3 ... b
3 ... 4 ... a
6 ... 7 ... c


In [7]:
for i in re.finditer('[^abc]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

1 ... 2 ... 7
4 ... 5 ... @
5 ... 6 ... k
7 ... 8 ... 9
8 ... 9 ... z
9 ... 10 ... x
10 ... 11 ...  


In [8]:
for i in re.finditer('[a-z]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
2 ... 3 ... b
3 ... 4 ... a
5 ... 6 ... k
6 ... 7 ... c
8 ... 9 ... z
9 ... 10 ... x


In [9]:
for i in re.finditer('[A-Z]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

In [10]:
for i in re.finditer('[a-zA-Z]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
2 ... 3 ... b
3 ... 4 ... a
5 ... 6 ... k
6 ... 7 ... c
8 ... 9 ... z
9 ... 10 ... x


In [11]:
for i in re.finditer('[0-9]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

1 ... 2 ... 7
7 ... 8 ... 9


In [12]:
for i in re.finditer('[a-zA-Z0-9]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
1 ... 2 ... 7
2 ... 3 ... b
3 ... 4 ... a
5 ... 6 ... k
6 ... 7 ... c
7 ... 8 ... 9
8 ... 9 ... z
9 ... 10 ... x


In [13]:
for i in re.finditer('[^a-zA-Z0-9]','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

4 ... 5 ... @
10 ... 11 ...  


**\d -Any numbers**

**\s - spaces**

**\S - Except space**

**\D - Except numbers**

**\w - Alphanumeric**

**\W - Except alphanumeric**

**. - All the characters including special characters**

In [14]:
for i in re.finditer('\d','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

1 ... 2 ... 7
7 ... 8 ... 9


In [15]:
for i in re.finditer('\s','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

10 ... 11 ...  


In [16]:
for i in re.finditer('\S','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
1 ... 2 ... 7
2 ... 3 ... b
3 ... 4 ... a
4 ... 5 ... @
5 ... 6 ... k
6 ... 7 ... c
7 ... 8 ... 9
8 ... 9 ... z
9 ... 10 ... x


In [17]:
for i in re.finditer('\D','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
2 ... 3 ... b
3 ... 4 ... a
4 ... 5 ... @
5 ... 6 ... k
6 ... 7 ... c
8 ... 9 ... z
9 ... 10 ... x
10 ... 11 ...  


In [18]:
for i in re.finditer('\w','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
1 ... 2 ... 7
2 ... 3 ... b
3 ... 4 ... a
5 ... 6 ... k
6 ... 7 ... c
7 ... 8 ... 9
8 ... 9 ... z
9 ... 10 ... x


In [19]:
for i in re.finditer('\W','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

4 ... 5 ... @
10 ... 11 ...  


In [20]:
for i in re.finditer('.','a7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... a
1 ... 2 ... 7
2 ... 3 ... b
3 ... 4 ... a
4 ... 5 ... @
5 ... 6 ... k
6 ... 7 ... c
7 ... 8 ... 9
8 ... 9 ... z
9 ... 10 ... x
10 ... 11 ...  


**In the below code we are looking for abc together**

In [22]:
for i in re.finditer('abc', 'abc7ba@kc9zx '):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 3 ... abc


**In the below code we are getting all the instances of c**

In [27]:
for i in re.finditer('c', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... c
2 ... 3 ... c
3 ... 4 ... c
5 ... 6 ... c
6 ... 7 ... c
7 ... 8 ... c


In [26]:
for i in re.finditer('[c]', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... c
2 ... 3 ... c
3 ... 4 ... c
5 ... 6 ... c
6 ... 7 ... c
7 ... 8 ... c


**In the below code we are looking for cd together however in the next code we are looking for either c or d**

In [28]:
for i in re.finditer('cd', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 2 ... cd
3 ... 5 ... cd
7 ... 9 ... cd


In [29]:
for i in re.finditer('[cd]', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... c
1 ... 2 ... d
2 ... 3 ... c
3 ... 4 ... c
4 ... 5 ... d
5 ... 6 ... c
6 ... 7 ... c
7 ... 8 ... c
8 ... 9 ... d


**The below code will give me atleast 1 c or any number of continous c's**

In [30]:
for i in re.finditer('c+', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... c
2 ... 4 ... cc
5 ... 8 ... ccc


**In this code we are getting any number of c's including 0**

In [31]:
for i in re.finditer('c*', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... c
1 ... 1 ... 
2 ... 4 ... cc
4 ... 4 ... 
5 ... 8 ... ccc
8 ... 8 ... 
9 ... 9 ... 


**In the below code we are getting atmost 1 c**

In [32]:
for i in re.finditer('c?', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... c
1 ... 1 ... 
2 ... 3 ... c
3 ... 4 ... c
4 ... 4 ... 
5 ... 6 ... c
6 ... 7 ... c
7 ... 8 ... c
8 ... 8 ... 
9 ... 9 ... 


**In the below code we are getting c{n} - n c's , in the below example we are getting 2 c's**

In [37]:
for i in re.finditer('c{2}', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

2 ... 4 ... cc
5 ... 7 ... cc


**In the below code we are getting c{n,m} i.e. either n numbers of c's or m number c's , in the below example we are getting 2 or 3 number of c's**

In [38]:
for i in re.finditer('c{2,3}', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

2 ... 4 ... cc
5 ... 8 ... ccc


**Except c**

In [39]:
for i in re.finditer('[^c]', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

1 ... 2 ... d
4 ... 5 ... d
8 ... 9 ... d


**It is checking if the string is starting with c or not**

In [42]:
for i in re.finditer('^c', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

0 ... 1 ... c


**When we are looking ending position of a string we can pass $, in the below example we are looking for if its ending with d or not**

In [43]:
for i in re.finditer('d$', 'cdccdcccd'):
    print(i.start(), '...', i.end(), '...', i.group())

8 ... 9 ... d


**Match() - It looks for characters from the start till any position**

In [50]:
string = 'Python is one of the most powerful languages'
lookingfor = input('What are you looking for: ')

if re.match(lookingfor,string)!=None:
    print('Match Found')
else:
    print('Match did not find')

What are you looking for: one
Match did not find


**Fullmatch() - It looks for characters from the start till the end**

In [53]:
string = 'Python is one of the most powerful languages'
lookingfor = input('What are you looking for: ')

if re.fullmatch(lookingfor,string)!=None:
    print('Match Found')
else:
    print('Match did not find')

What are you looking for: Python is one of the most powerful languages
Match Found


**Search() - It looks for any character in the string, you can search any character, there is no limitation that we have to look from the start or something**

In [56]:
string = 'Python is one of the most powerful languages'
lookingfor = input('What are you looking for: ')

if re.search(lookingfor,string)!=None:
    print('Match Found')
else:
    print('Match did not find')

What are you looking for: java
Match did not find


**Findall() - It will look for all the instances of the string which we are looking for**

In [61]:
resume = 'Python is powerful, Python is good, Python is the future, Python is open source'
keyword = input('What keyword are you looking for: ')

if len(re.findall(keyword, resume))>3:
    print('Your resume got selected')
else:
    print('Your resume got rejected')

What keyword are you looking for: Python
Your resume got selected


**Sub() - It will substitute the values which we want to replace**

In [62]:
resume = 'Python is powerful, Python is good, Python is the future, Python is open source'
whattochange = input('What you want to change: ')
Withwhat = input('What value you want: ')

re.sub(whattochange,Withwhat,resume)

What you want to change: Python
What value you want: Java


'Java is powerful, Java is good, Java is the future, Java is open source'

**Subn() - It will substitute the values which we want to replace, it will give the output in the form of a tuple, in that tuple we will have the replaced string and how many times the replacement happend that number will come**

In [63]:
resume = 'Python is powerful, Python is good, Python is the future, Python is open source'
whattochange = input('What you want to change: ')
Withwhat = input('What value you want: ')

re.subn(whattochange,Withwhat,resume)

What you want to change: Python
What value you want: Java


('Java is powerful, Java is good, Java is the future, Java is open source', 4)

**split() - It splits based on the delimiter**

In [64]:
re.split('-', '10-20-30-40-50-60')

['10', '20', '30', '40', '50', '60']

**\ is an escape character which can help python understand that . is not part of the code, it is a part of the string which we are looking for**

In [66]:
re.split('\.', 'www.iciciprulife.com')

['www', 'iciciprulife', 'com']

In [67]:
re.split('[.]', 'www.iciciprulife.com')

['www', 'iciciprulife', 'com']

In [68]:
string = 'Learning Python is very easy'
re.search('^Learn', string)

<re.Match object; span=(0, 5), match='Learn'>

In [69]:
re.search('easy$', string)

<re.Match object; span=(24, 28), match='easy'>

**IGNORECASE will ignore the case, it is making it case insensetive**

In [71]:
re.search('Easy$', string, re.IGNORECASE)

<re.Match object; span=(24, 28), match='easy'>

**1) Password Selection**

    a) The allowable characters should be
        a.1) Alphabets (A-Z,a-z)
        a.2) Digits (0-9)
        a.3) Hash - (#)
            
    b) First character should be a lowercase that too between (a-k)
    c) Second character should be a number which is divisble by 3 i.e. 0,3,6,9
    d) The length of the password 
        d.1) Should be exactly 5
        d.2) Should be minimum 5 

**Scenario 1** - Where the password length is exactly 5

In [75]:
password = input('Create the password: ')
if re.fullmatch('[a-k][0369][a-zA-Z0-9#]{3}',password)!=None:
    print('The password you selected is fine', password)
else:
    print('The password needs to be changed', password)

Create the password: a31234
The password needs to be changed a31234


**Scenario 2** - Where the password length is minimum 5

In [83]:
password = input('Create the password: ')
if re.fullmatch('[a-k][0369][a-zA-Z0-9#]{3,}',password)!=None:
    print('The password you selected is fine', password)
else:
    print('The password needs to be changed', password)

Create the password: a3###
The password you selected is fine a3###


**2) Pan Card Verification**

In [86]:
pancard = input('Enter the pancard number: ')
if re.fullmatch('[A-Z]{3}[CPHFATBLJG][A-Z][0-9]{4}[A-Z]',pancard):
    print('The pancard you passed is correct: ', pancard)
else:
    print('The pancard you passed is incorrect: ', pancard)

Enter the pancard number: 1AFUP1212K
The pancard you passed is incorrect:  1AFUP1212K


**3) Phone number verification**

In [87]:
phone = input('Enter the phone number: ')
if re.fullmatch('[6-9]\d{9}',phone)!=None:
    print('The phone number is valid', phone)
else:
    print('The phone number is invalid', phone)

Enter the phone number: 9643393302
The phone number is valid 9643393302


**4) Email check**

In [90]:
email = input('Enter the email: ')
if re.fullmatch('[a-zA-Z0-9_.]*@gmail[.]com',email)!=None:
    print('You are eligible for the offer')
else:
    print('You are not eligible for the offer')

Enter the email: rahul@yhoo.com
You are not eligible for the offer


In [91]:
email = input('Enter the email: ')
if re.fullmatch('[a-zA-Z0-9_.]*@(gmail|yahoo)[.]com',email)!=None:
    print('You are eligible for the offer')
else:
    print('You are not eligible for the offer')

Enter the email: rahul@yahoo.com
You are eligible for the offer


In [92]:
email = input('Enter the email: ')
if re.fullmatch('[a-zA-Z0-9_.]*@[a-zA-Z0-9]*[.]com',email)!=None:
    print('You are eligible for the offer')
else:
    print('You are not eligible for the offer')

Enter the email: rahul@iciciprulife.com
You are eligible for the offer


In [94]:
email = input('Enter the email: ')
if re.fullmatch('[a-zA-Z0-9_.]*@[a-zA-Z0-9]*[.][a-zA-Z]*',email)!=None:
    print('You are eligible for the offer')
else:
    print('You are not eligible for the offer')

Enter the email: rahul@gmail.in
You are eligible for the offer


**5) Reading the data from the site and get all the phone numbers**

In [96]:
import urllib.request
url = 'https://www.summet.com/dmsi/html/codesamples/addresses.html'
response = urllib.request.urlopen(url)
data = response.read()
data = data.decode()
data

'<html>\n<head>\n\t<title>Sample Addresses!</title>\n<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2760663110461940"\n     crossorigin="anonymous"></script>\n\n</head>\n<body>\n<h1> A page full of sample addresses for your parsing enjoyment!</h1>\n<h2> (All data is random....)</h2>\n<ul>\n\n<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2760663110461940"\n     crossorigin="anonymous"></script>\n<!-- summet.com-dmsi-addresses -->\n<ins class="adsbygoogle"\n     style="display:block"\n     data-ad-client="ca-pub-2760663110461940"\n     data-ad-slot="5472586510"\n     data-ad-format="auto"\n     data-full-width-responsive="true"></ins>\n<script>\n     (adsbygoogle = window.adsbygoogle || []).push({});\n</script>\n\n<li>Cecilia Chapman<br/>711-2880 Nulla St.<br/>Mankato Mississippi 96522<br/>(257) 563-7401</li>\n<li>Iris Watson<br/>P.O. Box 283 8562 Fusce Rd.<br/>Frederick Nebraska 20620<br/>

In [98]:
re.findall('\(\d{3}\) \d{3}-\d{4}',data)

['(257) 563-7401',
 '(372) 587-2335',
 '(786) 713-8616',
 '(793) 151-6230',
 '(492) 709-6392',
 '(654) 393-5734',
 '(404) 960-3807',
 '(314) 244-6306',
 '(947) 278-5929',
 '(684) 579-1879',
 '(389) 737-2852',
 '(660) 663-4518',
 '(608) 265-2215',
 '(959) 119-8364',
 '(468) 353-2641',
 '(248) 675-4007',
 '(939) 353-1107',
 '(570) 873-7090',
 '(302) 259-2375',
 '(717) 450-4729',
 '(453) 391-4650',
 '(559) 104-5475',
 '(387) 142-9434',
 '(516) 745-4496',
 '(326) 677-3419',
 '(746) 679-2470',
 '(455) 430-0989',
 '(490) 936-4694',
 '(985) 834-8285',
 '(662) 661-1446',
 '(802) 668-8240',
 '(477) 768-9247',
 '(791) 239-9057',
 '(832) 109-0213',
 '(837) 196-3274',
 '(268) 442-2428',
 '(850) 676-5117',
 '(861) 546-5032',
 '(176) 805-4108',
 '(715) 912-6931',
 '(993) 554-0563',
 '(357) 616-5411',
 '(121) 347-0086',
 '(304) 506-6314',
 '(425) 288-2332',
 '(145) 987-4962',
 '(187) 582-9707',
 '(750) 558-3965',
 '(492) 467-3131',
 '(774) 914-2510',
 '(888) 106-8550',
 '(539) 567-3573',
 '(693) 337-

# Numpy - Numerical Python Library or Package

**Website for Numpy** https://numpy.org/

**Its a well optimised C code which makes the processing faster**

In [99]:
import numpy as np

In [100]:
np.__version__

'1.21.5'

**Array is a basic data structure in numpy**

    When we want to do complex calculation we need numpy
        a) Creation of arrays
        b) Perform several operations on the arrays
        c) Integral calculus 
        d) Differential equations
        e) Statistics related operations

**What is an array**
    
    a) An indexed collection of homogenous data elements 
    
    b) It is most commonly used in the programming languages like c,c++ or java
    
    c) By default we dont have the array in Python, we have other data structures like list, tuple, etc


In [107]:
ages = [21,23,44,33,22,24,21]
type(ages)

list

In [108]:
ages_array = np.array(ages)
type(ages_array)

numpy.ndarray

**Similaries between Lists and Array**

    1) Both can be used to store the data

    2) The order will be preserved in both, indexing and slicing concepts will remain the same
    
    3) Both are mutable in nature, we can change the values
    

**Differences between Lists and Arrays**

    1) List is by default comes in with Python, however we need numpy package to get arrays
    
    2) List can contain heterogenous data however, arrays can have homogeneous data
    
    3) On the list we cannot perform vector operationsm we can do that in the arrays
    
    4) Arrays consumes less memory than lists
    
    5) Arrays are superfast when we compare it with lists
    
    6) Arrays are more convinient for doing complex mathematical calculations

In [112]:
ages*3

[21,
 23,
 44,
 33,
 22,
 24,
 21,
 21,
 23,
 44,
 33,
 22,
 24,
 21,
 21,
 23,
 44,
 33,
 22,
 24,
 21]

In [111]:
ages_array*3

array([ 63,  69, 132,  99,  66,  72,  63])

**In the array string takes the priority, if string is not there than float will takes the priority, if float is not there than integer will takes the priority, and last boolean takes the priority**

In [122]:
list1 = [True]

In [124]:
array1= np.array(list1)

In [125]:
array1

array([ True])

**Arrays are faster than lists**

In [127]:
sales = [3432,3321,2312,1433]
profit = [433,233,221,231]

for i in range(0,len(sales)):
    print(profit[i]/sales[i])

0.12616550116550115
0.07015959048479374
0.09558823529411764
0.1612002791346825


In [128]:
sales_array = np.array(sales)
profit_array = np.array(profit)

In [129]:
sales_array

array([3432, 3321, 2312, 1433])

In [130]:
profit_array

array([433, 233, 221, 231])

In [131]:
profit_array/sales_array

array([0.1261655 , 0.07015959, 0.09558824, 0.16120028])

In [135]:
sales_array[1]=2222

**Attributes** - Which is giving us the property of an array

In [139]:
sales_array.shape

(4,)

In [140]:
sales_array.size

4

In [141]:
sales_array.ndim

1

**Functions**

In [143]:
sales_array

array([3432, 2222, 2312, 1433])

In [142]:
sales_array.mean()

2349.75

**How to create a matrix - 2 dimension array**

In [144]:
sales_us = [4332,2112,2423,2111]
sales_eu = [4443,2332,1222,1122]
sales_ind = [4444,2232,1343,3333]

In [146]:
sales_matrix = np.array([sales_us,sales_eu,sales_ind])

In [147]:
sales_matrix

array([[4332, 2112, 2423, 2111],
       [4443, 2332, 1222, 1122],
       [4444, 2232, 1343, 3333]])

In [148]:
sales_matrix[2,2]

1343

In [152]:
sales_matrix[1:,1:3]

array([[2332, 1222],
       [2232, 1343]])

In [151]:
sales_matrix[1:3,1:3]

array([[2332, 1222],
       [2232, 1343]])

In [157]:
sales_matrix.T.shape

(4, 3)

In [156]:
sales_matrix.shape

(3, 4)

In [158]:
profit_us = [132,112,123,111]
profit_eu = [243,232,222,222]
profit_ind = [344,332,343,333]

In [159]:
profit_matrix = np.array([profit_us,profit_eu,profit_ind])

In [161]:
profit_matrix.shape

(3, 4)

In [162]:
sales_matrix

array([[4332, 2112, 2423, 2111],
       [4443, 2332, 1222, 1122],
       [4444, 2232, 1343, 3333]])

In [163]:
profit_matrix

array([[132, 112, 123, 111],
       [243, 232, 222, 222],
       [344, 332, 343, 333]])

In [165]:
np.round(profit_matrix/sales_matrix,2)

array([[0.03, 0.05, 0.05, 0.05],
       [0.05, 0.1 , 0.18, 0.2 ],
       [0.08, 0.15, 0.26, 0.1 ]])

In [166]:
np.round(profit_matrix+sales_matrix,2)

array([[4464, 2224, 2546, 2222],
       [4686, 2564, 1444, 1344],
       [4788, 2564, 1686, 3666]])

In [167]:
np.round(profit_matrix-sales_matrix,2)

array([[-4200, -2000, -2300, -2000],
       [-4200, -2100, -1000,  -900],
       [-4100, -1900, -1000, -3000]])

In [168]:
np.round(profit_matrix*sales_matrix,2)

array([[ 571824,  236544,  298029,  234321],
       [1079649,  541024,  271284,  249084],
       [1528736,  741024,  460649, 1109889]])

In [173]:
import pandas as pd

In [175]:
pd.DataFrame(sales_matrix,columns=['Q1','Q2','Q3','Q4'])

Q1    Q2    Q3    Q4
0  4332  2112  2423  2111
1  4443  2332  1222  1122
2  4444  2232  1343  3333

In [177]:
np.mean(sales_matrix)

2620.75

In [178]:
sales_matrix.mean()

2620.75

**When we are passing axis = 1 that means we are calculating the mean row by row**

In [179]:
np.mean(sales_matrix,axis=1)

array([2744.5 , 2279.75, 2838.  ])

**When we are passing axis = 0 that means we are calculating the mean column by column**

In [180]:
np.mean(sales_matrix,axis=0)

array([4406.33333333, 2225.33333333, 1662.66666667, 2188.66666667])

In [182]:
np.median(sales_matrix,axis=1)

array([2267.5, 1777. , 2782.5])

In [181]:
np.median(sales_matrix,axis=0)

array([4443., 2232., 1343., 2111.])

In [185]:
np.std(sales_matrix,axis=1)

array([ 925.32386222, 1336.1886796 , 1164.74482184])

In [183]:
np.std(sales_matrix,axis=0)

array([ 52.56318949,  89.93825042, 539.90143133, 904.30611828])

In [187]:
sales_matrix[np.where(sales_matrix>4000)]

array([4332, 4443, 4444])

In [189]:
sales_matrix

array([[4332, 2112, 2423, 2111],
       [4443, 2332, 1222, 1122],
       [4444, 2232, 1343, 3333]])

**In the below output the left part is the index of the rows and the right part is the index of the columns**

In [188]:
np.where(sales_matrix>4000)

(array([0, 1, 2], dtype=int64), array([0, 0, 0], dtype=int64))

# Pandas - To read the data from the external sources

In [190]:
import pandas as pd

In [191]:
pd.__version__

'1.4.4'

**Website for Pandas** https://pandas.pydata.org/

In [192]:
student_details = {'stuid':[1,2,3,4,5], 'stuname':['A','B','C','D','E'], 'sturegion':['N','S','S','E','W']}

In [193]:
student_details

{'stuid': [1, 2, 3, 4, 5],
 'stuname': ['A', 'B', 'C', 'D', 'E'],
 'sturegion': ['N', 'S', 'S', 'E', 'W']}

In [194]:
student_marks = {'stuid':[1,2,3,4,6], 'stusub':['Py','R','SQL','Py','Tab'], 'stumarks':[12,22,11,22,12]}

In [195]:
student_marks

{'stuid': [1, 2, 3, 4, 6],
 'stusub': ['Py', 'R', 'SQL', 'Py', 'Tab'],
 'stumarks': [12, 22, 11, 22, 12]}

In [196]:
df1 = pd.DataFrame(student_details)

In [197]:
df2 = pd.DataFrame(student_marks)

In [198]:
df1

stuid stuname sturegion
0      1       A         N
1      2       B         S
2      3       C         S
3      4       D         E
4      5       E         W

In [199]:
df2

stuid stusub  stumarks
0      1     Py        12
1      2      R        22
2      3    SQL        11
3      4     Py        22
4      6    Tab        12

**inner join** - Only common records with participate i.e. Stuid 1,2,3,4, By default merge give the output as a inner join. Joining is happening on the common column. We can use on= as well when there are multiple common columns but we want to join on any specific column. 

Lets assume there are 4 common columns, and I want to join on 2 common columns in that case we will write on=['stuid','stuname']

In [208]:
pd.merge(df1,df2,on=['stuid'],how='inner')

stuid stuname sturegion stusub  stumarks
0      1       A         N     Py        12
1      2       B         S      R        22
2      3       C         S    SQL        11
3      4       D         E     Py        22

**left outer join** - All the records from the left table will participate and matching records from the right table will participate. Also, the table which we are putting first in the bracket python considers that as a left table

In [207]:
pd.merge(df1,df2,on='stuid',how='left')

stuid stuname sturegion stusub  stumarks
0      1       A         N     Py      12.0
1      2       B         S      R      22.0
2      3       C         S    SQL      11.0
3      4       D         E     Py      22.0
4      5       E         W    NaN       NaN

**right outer join** - All the records from the right table will participate and matching records from the left table will participate. Also, the table which we are putting second in the bracket python considers that as a right table

In [209]:
pd.merge(df1,df2,on='stuid',how='right')

stuid stuname sturegion stusub  stumarks
0      1       A         N     Py        12
1      2       B         S      R        22
2      3       C         S    SQL        11
3      4       D         E     Py        22
4      6     NaN       NaN    Tab        12

**full outer join** - All the records from both the tables will participate.

In [210]:
pd.merge(df1,df2,on='stuid',how='outer')

stuid stuname sturegion stusub  stumarks
0      1       A         N     Py      12.0
1      2       B         S      R      22.0
2      3       C         S    SQL      11.0
3      4       D         E     Py      22.0
4      5       E         W    NaN       NaN
5      6     NaN       NaN    Tab      12.0

In [211]:
student_details = {'stuid':[1,2,3,4,5], 'stuname':['A','B','C','D','E'], 'sturegion':['N','S','S','E','W']}
student_marks = {'stu_id':[1,2,3,4,6], 'stusub':['Py','R','SQL','Py','Tab'], 'stumarks':[12,22,11,22,12]}

In [212]:
df1 = pd.DataFrame(student_details)
df2 = pd.DataFrame(student_marks)

In [213]:
df1

stuid stuname sturegion
0      1       A         N
1      2       B         S
2      3       C         S
3      4       D         E
4      5       E         W

In [214]:
df2

stu_id stusub  stumarks
0       1     Py        12
1       2      R        22
2       3    SQL        11
3       4     Py        22
4       6    Tab        12

**When we have the different column names we can go with left_on and right_on**

In [216]:
pd.merge(df1,df2,left_on='stuid',right_on='stu_id',how='inner')

stuid stuname sturegion  stu_id stusub  stumarks
0      1       A         N       1     Py        12
1      2       B         S       2      R        22
2      3       C         S       3    SQL        11
3      4       D         E       4     Py        22

In [217]:
pd.merge(df1,df2,left_on='stuid',right_on='stu_id',how='left')

stuid stuname sturegion  stu_id stusub  stumarks
0      1       A         N     1.0     Py      12.0
1      2       B         S     2.0      R      22.0
2      3       C         S     3.0    SQL      11.0
3      4       D         E     4.0     Py      22.0
4      5       E         W     NaN    NaN       NaN

In [218]:
pd.merge(df1,df2,left_on='stuid',right_on='stu_id',how='right')

stuid stuname sturegion  stu_id stusub  stumarks
0    1.0       A         N       1     Py        12
1    2.0       B         S       2      R        22
2    3.0       C         S       3    SQL        11
3    4.0       D         E       4     Py        22
4    NaN     NaN       NaN       6    Tab        12

In [219]:
pd.merge(df1,df2,left_on='stuid',right_on='stu_id',how='outer')

stuid stuname sturegion  stu_id stusub  stumarks
0    1.0       A         N     1.0     Py      12.0
1    2.0       B         S     2.0      R      22.0
2    3.0       C         S     3.0    SQL      11.0
3    4.0       D         E     4.0     Py      22.0
4    5.0       E         W     NaN    NaN       NaN
5    NaN     NaN       NaN     6.0    Tab      12.0

**When we have 3 tables how can we join all those together**

In [220]:
customer_table = {'cust_id':[1,2,3,4,5], 'cust_name':['A','B','C','D','E'], 'cust_region':['N','S','S','W','E']}

loan_table = {'cust_id':[1,2,3,4,5],'loan_id':[10,20,30,40,50],'loan_amt':[123,321,132,134,222]}

agent_table = {'agent_id':[101,102,101,102,102], 'agent_name':['James','John','James','John','John'], 'loan_id':[10,20,30,40,50]}

In [221]:
df1 = pd.DataFrame(customer_table)

In [222]:
df2 = pd.DataFrame(loan_table)

In [223]:
df3 = pd.DataFrame(agent_table)

In [224]:
df1

cust_id cust_name cust_region
0        1         A           N
1        2         B           S
2        3         C           S
3        4         D           W
4        5         E           E

In [225]:
df2

cust_id  loan_id  loan_amt
0        1       10       123
1        2       20       321
2        3       30       132
3        4       40       134
4        5       50       222

In [226]:
df3

agent_id agent_name  loan_id
0       101      James       10
1       102       John       20
2       101      James       30
3       102       John       40
4       102       John       50

In [228]:
pd.merge(pd.merge(df1,df2),df3)

cust_id cust_name cust_region  loan_id  loan_amt  agent_id agent_name
0        1         A           N       10       123       101      James
1        2         B           S       20       321       102       John
2        3         C           S       30       132       101      James
3        4         D           W       40       134       102       John
4        5         E           E       50       222       102       John

# Union & Union all & Index Join

In [229]:
customer_table_US = {'cust_id':[1,2,3,4,5], 'cust_name':['A','B','C','D','E'], 'cust_region':['N_US','S_US','S_US','W_US','E_US']}

In [230]:
customer_table_US

{'cust_id': [1, 2, 3, 4, 5],
 'cust_name': ['A', 'B', 'C', 'D', 'E'],
 'cust_region': ['N_US', 'S_US', 'S_US', 'W_US', 'E_US']}

In [231]:
customer_table_IND = {'cust_id':[6,7,8,9,5], 'cust_name':['P','Q','R','S','E'], 'cust_region':['N_IND','S_IND','S_IND','W_IND','E_US']}

In [232]:
customer_table_IND

{'cust_id': [6, 7, 8, 9, 5],
 'cust_name': ['P', 'Q', 'R', 'S', 'E'],
 'cust_region': ['N_IND', 'S_IND', 'S_IND', 'W_IND', 'E_US']}

In [233]:
cust_us = pd.DataFrame(customer_table_US)

In [234]:
cust_us

cust_id cust_name cust_region
0        1         A        N_US
1        2         B        S_US
2        3         C        S_US
3        4         D        W_US
4        5         E        E_US

In [235]:
cust_in = pd.DataFrame(customer_table_IND)

In [236]:
cust_in

cust_id cust_name cust_region
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US

**Union all - Where duplicates are entertained**

**When we are passing axis=0, that means its a union or union all**

In [239]:
pd.concat([cust_us,cust_in],axis=0)

cust_id cust_name cust_region
0        1         A        N_US
1        2         B        S_US
2        3         C        S_US
3        4         D        W_US
4        5         E        E_US
0        6         P       N_IND
1        7         Q       S_IND
2        8         R       S_IND
3        9         S       W_IND
4        5         E        E_US

**When we are passing axis=1 then it is index join**

In [240]:
pd.concat([cust_us,cust_in],axis=1)

cust_id cust_name cust_region  cust_id cust_name cust_region
0        1         A        N_US        6         P       N_IND
1        2         B        S_US        7         Q       S_IND
2        3         C        S_US        8         R       S_IND
3        4         D        W_US        9         S       W_IND
4        5         E        E_US        5         E        E_US

**Union - Where duplicates are not entertained**

**We are using nested functions to do the tasks, however we can do in step by step also, so doing this as single it will memory efficient as we are not creating the copies of the data, if you dont want to create the copies of the data we can overwrite the data in every step. Also while dropping the column we are passing axis=1 i.e. we are dropping the index column, that means when we want to drop a column we can pass axis=1**

In [246]:
final_output = pd.concat([cust_us,cust_in]).reset_index().drop('index',axis=1).drop_duplicates()

In [253]:
final_output.to_csv('today_data.csv')

**os is the operating system module which can help us to connect and play with the files in the local machine**

**Getcwd is a function which is showing us the Get Current Working Directory**

**Chdir is a function which is helping us to Change the Directory**

In [252]:
import os 
os.getcwd()

'C:\\Users\\rahul\\OneDrive\\Desktop'

In [251]:
os.chdir(r'C:\Users\rahul\OneDrive\Desktop')